### ISSUE TITLE
Extracted entities deterministic? 

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/DoSeR#3]
When preparing some screencasts it happened that entities for one paragraph were different than some minutes before. Is this expected? Is there some random component in the algorithm? If not I'll prepare a concrete example showing this difference.

**Comment by quhfus** [comment]
Yes indeed, there is one ;) But only for the main topic. The standard named entity disambiguation should be deterministic. The main topic extraction is based on doc2vec, which uses a random generator to infer the text. Hence, two main topics may alternate if both are relevant. 

I have already discussed this with the gensim/doc2vec authors
https://github.com/piskvorky/gensim/issues/447

**Comment by chseifert** [comment]
In an offline talk you told me that there is the possibility to enforce the main topic being extracted deterministically and that there is no difference (at least that we know of) in accuracy. Could we switch to that behaviour? It would i) make demos much more easy (because replicable), and ii) being deterministic would be more easily to explain to end users (I want to avoid getting question like "why does this extract A once and B the next time I am there"), and iii) we could also better see the influence of the personalisation step.

**Comment by quhfus** [comment]
That would be no problem. However, I'm just wondering about the frequent changings of the main topic. Basically, this should only happen if two topics are equally "likely". Are you always showing the same paragraphs, or does this problem often occur in different situations. 

But changing the algorithm is a one-click story ;)

**Comment by chseifert** [comment]
It's not that frequent, but I don't have quantitative values. Mostly I am using the Ada Lovelace wiki page for demos, because I know the background. And there it sometimes the main topics switches between Lord Byron and Ada Lovelace (and it might be Murphy that this happens in demos and feels more often than it is. ;-) 
But for a quantitative analysis I wouldn't use the user interface ;-) And the question is - do we need this?

**Comment by quhfus** [comment]
Haha okidoki. I will change that ;)
